export default {
  users: [
    {
      id: 1,
      first_name: "Bob",
      email: "bob@email.com",
      password: "password",
      specialties: [
        "Boat Diver",
        "Deep Diver",
        "Digital Underwater Photographer",
      ],
      instructorSpecialties: [],
      wishlist: [
        "Whale Shark",
        "Mola Mola",
        "Hammerhead Shark",
        "Great White Shark",
        "Tiger Shark",
      ],
      wishlistFulfilled: [
        "Whale Shark",
        "Manta Ray",
        "Great White Shark",
        "Blue-Ringed Octopus",
        "Mandarin Fish",
        "Seahorse",
        "Thresher Shark",
        "Frog Fish",
      ],
    },
  ],
  certs: [
    {
      id: 1,
      user_id: 1,
      agency: "PADI",
      certLevel: "Open Water Diver",
      certNum: "123ab45",
      certDate: "May 2020",
    },
  ],
  dives: [
    {
      id: 1,
      user_id: 1,
      date: "2020-05-04",
      country: "United States of America",
      region: "Hawaii",
      diveSite: "Mana Crack",
      maxDepth: 100,
      duration: 56,
      waterTemp: 72,
      diveShop: "Bubbles Below",
      guide: "Ben",
      buddy: "Chris",
      viz: 4,
      diveType: "Boat",
      driftDive: true,
      nightDive: false,
      description:
        "Lots of old dead coral, but found some sweet nudis and a whitetip.",
      animalsSpotted: [],
      rating: 3,
    },
    {
      id: 2,
      user_id: 1,
      date: "2020-05-04",
      country: "United States of America",
      region: "Hawaii",
      diveSite: "Mana Crack",
      maxDepth: 95,
      duration: 58,
      waterTemp: 73,
      diveShop: "Bubbles Below",
      guide: "Ben",
      buddy: "Chris",
      viz: 3,
      diveType: "Boat",
      driftDive: true,
      nightDive: false,
      description:
        "Strong current, fast drift. Mostly just floated and watched the world go by.",
      animalsSpotted: ["Manta Ray", "Great White Shark"],
      rating: 3,
    },
    {
      id: 3,
      user_id: 1,
      date: "2017-03-18",
      country: "Philippines",
      region: "Malapascua",
      diveSite: "North Point",
      maxDepth: 79,
      duration: 50,
      waterTemp: 77,
      diveShop: "Thresher Shark Divers",
      guide: "",
      buddy: "",
      viz: "",
      diveType: "boat",
      driftDive: false,
      nightDive: false,
      description:
        "Saw some teeny tiny shrimp: flea-sized, solid red coloring, half a dozen. Juveniles? On the other end of the spectrum, saw some huge nudis.",
      animalsSpotted: [],
      rating: 3,
    },
    {
      id: 4,
      user_id: 1,
      date: "2017-03-19",
      country: "Philippines",
      region: "Malapascua",
      diveSite: "Monad Shoal",
      maxDepth: 95,
      duration: 59,
      waterTemp: 77,
      diveShop: "Thresher Shark Divers",
      guide: "",
      buddy: "",
      viz: "",
      diveType: "boat",
      driftDive: false,
      nightDive: false,
      description:
        "No threshers. Mantis shrimp, eagle rays, pipefish, white tip, white/blue nudi, free swimming flatworm.",
      animalsSpotted: [],
      rating: 4,
    },
    {
      id: 5,
      user_id: 1,
      date: "2017-03-19",
      country: "Philippines",
      region: "Malapascua",
      diveSite: "Bantigue",
      maxDepth: 51,
      duration: 64,
      waterTemp: 79,
      diveShop: "Thresher Shark Divers",
      guide: "",
      buddy: "",
      viz: "",
      diveType: "boat",
      driftDive: false,
      nightDive: false,
      description:
        "Blue-Ringed Octopus! Tiger pipefish, mantis shrimp, rhino nudis, lionfish, cleaner shrimp.",
      animalsSpotted: ["Blue-Ringed Octopus"],
      rating: 4,
    },
    {
      id: 6,
      user_id: 1,
      date: "2017-03-20",
      country: "Philippines",
      region: "Malapascua",
      diveSite: "Lighthouse",
      maxDepth: 37,
      duration: 54,
      waterTemp: 75,
      diveShop: "Thresher Shark Divers",
      guide: "",
      buddy: "",
      viz: "",
      diveType: "boat",
      driftDive: false,
      nightDive: true,
      description: "Mandarin fish x2! Bobtail squid, seahorses x3, nudis.",
      animalsSpotted: ["Mandarin Fish", "Seahorse"],
      rating: 4,
    },
    {
      id: 7,
      user_id: 1,
      date: "2017-03-21",
      country: "Philippines",
      region: "Malapascua",
      diveSite: "Monad Shoal",
      maxDepth: 88,
      duration: 51,
      waterTemp: 77,
      diveShop: "Thresher Shark Divers",
      guide: "",
      buddy: "",
      viz: "",
      diveType: "boat",
      driftDive: false,
      nightDive: false,
      description:
        "Thresher! Cuttlefish, nudis, white tip, frog fish, baby lionfish, tiny cuttlefish? maybe bobtail squid",
      animalsSpotted: ["Thresher Shark", "Frog Fish"],
      rating: 5,
    },
  ],
  countries: [
    {
      country_name: "United States of America",
      regions: ["Hawaii", "Pacific Northwest", "Florida", "Channel Islands"],
    },
    {
      country_name: "Mexico",
      regions: ["Riviera Maya", "Baja", "Revillagigedo Islands"],
    },
    {
      country_name: "Australia",
      regions: [
        "Great Barrier Reef",
        "SS Yongala",
        "Western Australia",
        "Tasmania",
      ],
    },
    {
      country_name: "Nicaragua",
      regions: ["Corn Islands"],
    },
    {
      country_name: "Cayman Islands",
      regions: [
        "Little Cayman",
        "Cayman Brac",
        "Grand Cayman, West",
        "Grand Cayman, East",
        "Grand Cayman, North",
      ],
    },
    {
      country_name: "Thailand",
      regions: [
        "Similan Islands",
        "Chumphon Archipelago (Koh Tao, Koh Samui, Koh Phangan)",
        "Krabi (Koh Lanta)",
        "Phuket",
      ],
    },
    {
      country_name: "Indonesia",
      regions: [
        "Bali (Nusa Lembongan, Nusa Penida)",
        "Gili Islands",
        "Raja Ampat",
        "Komodo National Park",
        "Manado",
      ],
    },
    {
      country_name: "Philippines",
      regions: [
        "Malapascua",
        "Puerto Galera",
        "Coron",
        "Bohol",
        "El Nido",
        "Boracay",
        "Apo Reef",
      ],
    },
  ],
  animals: [
    {
      id: 1,
      animal: "Whale Shark",
      isChecked: false,
    },
    {
      id: 2,
      animal: "Mola Mola",
      isChecked: false,
    },
    {
      id: 3,
      animal: "Thresher Shark",
      isChecked: false,
    },
    {
      id: 4,
      animal: "Hammerhead Shark",
      isChecked: false,
    },
    {
      id: 5,
      animal: "Great White Shark",
      isChecked: false,
    },

    {
      id: 6,
      animal: "Tiger Shark",
      isChecked: false,
    },
    {
      id: 7,
      animal: "Manatee",
      isChecked: false,
    },
    {
      id: 8,
      animal: "Manta Ray",
      isChecked: false,
    },
    {
      id: 9,
      animal: "Seahorse",
      isChecked: false,
    },
    {
      id: 10,
      animal: "Dragon Moray",
      isChecked: false,
    },
    {
      id: 11,
      animal: "Ribbon Eel",
      isChecked: false,
    },
    {
      id: 12,
      animal: "Mandarin Fish",
      isChecked: false,
    },
    {
      id: 13,
      animal: "Frog Fish",
      isChecked: false,
    },
    {
      id: 14,
      animal: "Mimic Octopus",
      isChecked: false,
    },
    {
      id: 15,
      animal: "Pygmy Seahorse",
      isChecked: false,
    },
    {
      id: 16,
      animal: "Leafy Seadragon",
      isChecked: false,
    },
    {
      id: 17,
      animal: "Blue-Ringed Octopus",
      isChecked: false,
    },
    {
      id: 18,
      animal: "Flamboyant Cuttlefish",
      isChecked: false,
    },
    {
      id: 19,
      animal: "Harlequin Shrimp",
      isChecked: false,
    },
    {
      id: 20,
      animal: "Orangutan Crab",
      isChecked: false,
    },
    {
      id: 21,
      animal: "Ornate Ghost Pipefish",
      isChecked: false,
    },
    {
      id: 22,
      animal: "Leaf Scorpionfish",
      isChecked: false,
    },
  ],
  animalTracker: [
    {
      id: 1,
      animal: "Manta Ray",
      country: "United States of America",
      region: "Hawaii",
    },
    {
      id: 2,
      animal: "Whale Shark",
      country: "United States of America",
      region: "Hawaii",
    },
    {
      id: 3,
      animal: "Whale Shark",
      country: "Thailand",
      region: "Chumphon Archipelago (Koh Tao, Koh Samui, Koh Phangan)",
    },
    {
      id: 4,
      animal: "Whale Shark",
      country: "Australia",
      region: "SS Yongala",
    },
    {
      id: 5,
      animal: "Whale Shark",
      country: "Australia",
      region: "SS Yongala",
    },
    {
      id: 6,
      animal: "Manta Ray",
      country: "Australia",
      region: "SS Yongala",
    },
    {
      id: 7,
      animal: "Blue-Ringed Octopus",
      country: "Philippines",
      region: "Malapascua",
    },
    {
      id: 8,
      animal: "Mandarin Fish",
      country: "Philippines",
      region: "Malapascua",
    },
    {
      id: 9,
      animal: "Seahorse",
      country: "Philippines",
      region: "Malapascua",
    },
    {
      id: 10,
      animal: "Thresher Shark",
      country: "Philippines",
      region: "Malapascua",
    },
    {
      id: 11,
      animal: "Frog Fish",
      country: "Philippines",
      region: "Malapascua",
    },
  ],
  specialties: [
    { id: 1, name: "Altitude Diver", isChecked: false },
    { id: 2, name: "Boat Diver", isChecked: false },
    { id: 3, name: "Cavern Diver", isChecked: false },
    { id: 4, name: "Coral Reef Conservation", isChecked: false },
    { id: 5, name: "Deep Diver", isChecked: false },
    { id: 6, name: "Digital Underwater Photographer", isChecked: false },
    { id: 7, name: "Diver Propulsion Vehicle", isChecked: false },
    { id: 8, name: "Drift Diver", isChecked: false },
    { id: 9, name: "Dry Suit Diver", isChecked: false },
    { id: 10, name: "Emergency Oxygen Provider", isChecked: false },
    { id: 11, name: "Enriched Air Diver", isChecked: false },
    { id: 12, name: "Equipment Specialist", isChecked: false },
    { id: 13, name: "Fish Identification", isChecked: false },
    { id: 14, name: "Ice Diver", isChecked: false },
    { id: 15, name: "Night Diver", isChecked: false },
    { id: 16, name: "Peak Performance Buoyancy", isChecked: false },
    { id: 17, name: "Public Safety Diver", isChecked: false },
    { id: 18, name: "Search and Recovery Diver", isChecked: false },
    { id: 19, name: "Self-Reliant Diver", isChecked: false },
    { id: 20, name: "Sidemount Diver", isChecked: false },
    { id: 21, name: "Underwater Naturalist", isChecked: false },
    { id: 22, name: "Underwater Navigator", isChecked: false },
    { id: 23, name: "Underwater Videographer", isChecked: false },
    { id: 24, name: "Wreck Diver", isChecked: false },
  ],
};
